version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      target: local
    tty: true
    volumes:
      - ./nginx:/usr/share/nginx/html
    ports:
      - 80:80
  php_apache:
    build:
      context: ./php_apache
      dockerfile: Dockerfile
      target: local
    volumes:
      - ./php_apache:/var/www/html
    working_dir: /var/www/html
    tty: true
    ports:
      - 81:80
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
      target: local
    volumes:
      - ./laravel:/var/www/html
    working_dir: /var/www/html
    tty: true
    ports:
      - 82:80
  lumen:
    build:
      context: ./lumen
      dockerfile: Dockerfile
      target: local
    volumes:
      - ./lumen:/var/www/html
    working_dir: /var/www/html
    tty: true
    ports:
      - 83:80
